- name: Create or ensure EC2 resources exist
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_name: disorganizer
    key_name: ITM350
    security_group_name: disorganized-sg
    instance_type: t2.micro
    region: us-east-1
    tag_name: disorganized
  roles:
    - pro_build


- name: checkmk
  hosts: dynamic_ec2
  become: true
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    checkmk_version: "2.2.0p17"
    checkmk_package: "check-mk-raw-2.2.0p17_0.focal_amd64.deb"
    checkmk_url: "https://download.checkmk.com/checkmk/{{ checkmk_version }}/{{ checkmk_package }}"
    pubkey_url: "https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg"
    download_dir: "/home/admin"
  roles:
    - pro_checkmk