---

- name: Update Message of the Day
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Install Checkmk
  block:
    - name: Install Docker dependencies
      apt:
        name: 
          - docker.io
          - docker-compose
        update_cache: yes
        state: present

    - name: Create persistent data directory
      file:
        path: /opt/checkmk_data
        state: directory
        mode: '0755'

    - name: Pull Checkmk Docker image
      docker_image:
        name: "{{ checkmk_image }}"
        source: pull

    - name: Deploy Checkmk container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ checkmk_image }}"
        state: started
        restart_policy: always
        volumes:
          - "/opt/checkmk_data:/omd/sites"
        ports:
          - "{{ web_port }}:5000/tcp"
          - "{{ agent_port }}:8000/tcp"
        tmpfs:
          - "/opt/omd/sites/cmk/tmp:uid=1000,gid=1000"

    - name: Set Checkmk admin password
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: |
          omd su cmk -c 'cmk-passwd cmkadmin -i <<EOF
          swordfish
          swordfish
          EOF'

  # # - name: Add Ubuntu security repository
  # #   become: yes
  # #   apt_repository:
  # #     repo: "deb http://security.ubuntu.com/ubuntu focal-security main universe"
  # #     state: present
  # #     filename: ubuntu-focal-security

  # # - name: Update apt cache
  # #   become: yes
  # #   apt:
  # #     update_cache: yes

  # - name: Install required packages
  #   apt:
  #     name:
  #       - wget
  #       - figlet
  #       - gnupg
  #       - perl
  #     state: present
  #     update_cache: true
  #   become: yes

  # - name: Update Message of the Day
  #   template:
  #     src: motd.j2
  #     dest: /etc/motd
  #     owner: root
  #     group: root
  #     mode: '0644'

  # - name: Download Checkmk .deb package
  #   get_url:
  #     url: "{{ checkmk_url }}"
  #     dest: "{{ download_dir }}/{{ checkmk_package }}"
  #     mode: '0644'

  # - name: Download Checkmk public key
  #   get_url:
  #     url: "{{ pubkey_url }}"
  #     dest: "{{ download_dir }}/Check_MK-pubkey.gpg"
  #     mode: '0644'

  # - name: Import Checkmk public key
  #   ansible.builtin.apt_key:
  #     url: "{{ pubkey_url }}"
  #     state: present

  # - name: Install Checkmk package
  #   apt:
  #     deb: "{{ download_dir }}/{{ checkmk_package }}"

  # - name: Setup CheckMK site
  #   command: omd create DisOrganizer
  #   args:
  #     creates: "/opt/omd/sites/DisOrganizer"

  # - name: Allow external access
  #   command: omd config DisOrganizer set APACHE_TCP_ADDR 0.0.0.0

  # - name: Update Apache config
  #   command: omd update-apache-config DisOrganizer

  # - name: Start CheckMK site
  #   command: omd start DisOrganizer